### PR TITLE
Complete rewrite of the bot.

### PR DESCRIPTION
**Pull request by spinfish**
### Summary

In this PR I have completely rewritten the WorldTime bot.
The four main concerns I have addressed are explained in the following bulletpoints.

- Uses discord.py commands extension:
Rather than the previous command system that was purely based on an `on_message` event, I find that using  `ext.commands` provides a far more dynamic and clean approach to creating commands for your bot. This is because it supports adding checks to your commands, cooldowns, and so much more than just a simple `on_message` event. It's probably a lot faster, too.

- Subclasses commands.AutoShardedBot:
This inherits all functionality from both `commands.Bot` and `discord.AutoShardedClient`, which means you don't need to deal with/worry about sharding if the bot were to ever grow above 1000 servers or losing functionality from `commands.Bot` (I noticed a few of your comments in the code where concerned about sharding).

 - Switched to asyncpg from psycopg2:
This is because the `psycopg2` module is **blocking**, meaning that whenever code using it is run it blocks the entire event             
loop, meaning that the bot cannot process other events, such as messages, during the time that the blocking code is running. There are hacks to make synchronous code run "asynchronously", but it's much better to use something that is already asynchronous (such as `asyncpg`, which has a very nice API) if possible.
        
 - Improved code formatting:
Before, the code was quite hard to read and not as efficient as it could be. I believe I have improved how the code looks and its efficiency with this PR.

### Checklist

- [x] Actually tested the code?
I have tested the code and everything seems to be working very smoothly. This PR is completely ready to be merged with your repo now! :)

### CODE REVIEW

**Comment by stacey2004uk** [comment]
Fantastic job on the rewrite SpinFish, 10/10 xD
The bot seems to respond more quickly now too
SpinFish = Noi ?

**Comment by spinfish** [comment]
> Fantastic job on the rewrite SpinFish, 10/10 xD
> The bot seems to respond more quickly now too
> I also noticed you addressed the sharding issue too
> 
> Subclasses commands.AutoShardedBot:
> This inherits all functionality from both commands.Bot and discord.AutoShardedClient, which means you don't need to deal with/worry about sharding if the bot were to ever grow above 1000 servers or losing functionality from commands.Bot.
> 
> Excellent job!
> 
> SpinFish = Noi ?
 
hey thanks so much!! yeah there's still a few tweaks that need to be applied, it should be all finished by tomorrow though :)

**Comment by NoiTheCat** [comment]
Ahh, hey there! Apologies for taking so long to respond to this, with life and other priorities constantly getting in the way. I was quite surprised the other day to find this among my notifications, as I never would have expected to get a PR like this...

I feel like I should apologize for my coding decisions you've likely run into, as this came about as a learning exercise in which I took my usual approach and tried to hastily apply it here without much consultation aside from attempting to understand the library documentation. If it's no problem, I'd like to take a little longer and make time to look over the redone code and possibly ask a few questions before I merge it.

Thank you very much for this contribution!

**Comment by spinfish** [comment]
> Ahh, hey there! Apologies for taking so long to respond to this, with life and other priorities constantly getting in the way. I was quite surprised the other day to find this among my notifications, as I never would have expected to get a PR like this...
> 
> I feel like I should apologize for my coding decisions you've likely run into, as this came about as a learning exercise in which I took my usual approach and tried to hastily apply it here without much consultation aside from attempting to understand the library documentation. If it's no problem, I'd like to take a little longer and make time to look over the redone code and possibly ask a few questions before I merge it.
> 
> Thank you very much for this contribution!

ahhh sorry for not responding to this sooner!! you're fine, i understand if you're busy! yeah i can imagine your surprise as this PR :') and i don't think there's any need to apologize for your code, everyone makes mistakes :) it's completely fine that you take a look at the code, i completely understand. and you're welcome for the PR, i really enjoyed it!!

**Comment by rzhao271** [comment]
@spinfish I like how you highlighted the issues of the bot; they would make for good issues to file under https://github.com/NoiTheCat/WorldTime/issues.

However, the PR (including even just the first commit) seems to change too much at once, so I don't think it's very easy to review and merge.
If you want the changes to be merged still, I suggest you create several PRs that iteratively update the bot, rather than one large PR that fixes all the issues at the same time.

**Comment by NoiTheCat** [comment]
Hello! I do apologize for taking such a long time to follow up. I am inclined to agree with @rzhao271, it has been difficult for me to come around to it in large part because your PR does far too much at once for it to be manageable.

Your work and efforts are very appreciated, and I am willing to consider them if they were presented more cleanly - on an issue-by-issue basis as incremental changes or otherwise as focused improvements submitted with a proper in-depth explanation. And please, keep further commits and changes to a minimum once you've submitted the PR. As it was done here, it comes off as unorganized, as if you rushed your code and sent an incomplete version when you first submitted it, and it puts a greater workload on me when it comes to conducting a review of your code.

Being presented with a complete rewrite out of the blue like this was a surprise, and one I had no preparations or expectations for. I've discussed this with a small number of people and they're in agreement, that this is a bit excessive to accept all at once and is not something that's typically requested out of a PR without at least having some sort of relationship or agreement with a project's owner/team beforehand. I can't fault you for being ambitious though. Plus your skill and familiarity with Python are worth me giving my praise, and the ideas and insights that I've gleamed when looking through your code are certainly very helpful!

Though I am considering rejecting this PR, I encourage you to organize your changes in a way that makes it easier on both of us to introduce such changes into the bot in a more gradual or incremental way, allowing us to discuss, consider, and test the changes on a case by case basis rather than an entire lump sum at once. I'd be quite happy to follow up with you regarding your improvements that way.
And once again, thank you very much!

**Comment by spinfish** [comment]
> Hello! I do apologize for taking such a long time to follow up. I am inclined to agree with @rzhao271, it has been difficult for me to come around to it in large part because your PR does far too much at once for it to be manageable.
this is an issue on my part, i acted on impulse a bit with submitting this and should have taken your perspective into consideration a bit more... i'm very sorry about that.

> Your work and efforts are very appreciated, and I am willing to consider them if they were presented more cleanly - on an issue-by-issue basis as incremental changes or otherwise as focused improvements submitted with a proper in-depth explanation. And please, keep further commits and changes to a minimum once you've submitted the PR. As it was done here, it comes off as unorganized, as if you rushed your code and sent an incomplete version when you first submitted it, and it puts a greater workload on me when it comes to conducting a review of your code.
i apologize for the amount of commits i made after submitting it, i realize now that it does indeed come off like the original job was rushed.

> Though I am considering rejecting this PR, I encourage you to organize your changes in a way that makes it easier on both of us to introduce such changes into the bot in a more gradual or incremental way, allowing us to discuss, consider, and test the changes on a case by case basis rather than an entire lump sum at once. I'd be quite happy to follow up with you regarding your improvements that way.
yes, sure, i'd be happy to go through this step by step rather than in one huge lump like i did before, how would you like to go about doing that? do i start making issues on the original repo on things that i think need to be changed, file by file?

> And once again, thank you very much!
 you are most welcome!

**Comment by spinfish** [comment]
I'm still up for improving the PR...

**Comment by NoiTheCat** [comment]
Hiya,

Due to discord.py having been discontinued and my own difficulties in maintaining different bots in different languages while wanting to share improvements between each project more easily, I have ported the project over from Python to C#. I apologize for not getting back to you sooner - my personal life tends to be hectic and unpredictable and I am not the best at following up with everything going on all around me.

As I mentioned, I would have accepted if you reworked your PR in a more structured way. Glancing at your code again, I'm once again seeing that it is very excellent, very clean, and you have a very strong and solid grasp on how Python and the library are meant to be used. I really regret abandoning it because of it all. I greatly encourage you to keep it up - and not let my own failure to react properly to this PR discourage you from doing something similar to this again with another project, or with any that you have of your own.

Once more, thank you very much! I really appreciate this, and I apologize that I wasn't able to make use of it in the end. I wish you the best with your future endeavors.

**Pull request closed without merging**
